version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cats-testwork
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lexa2015
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: